# -*- coding: utf-8 -*-
"""Alejandra_Jofre_Ejercicio2pynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/AleBelen/9ac3e9bf0a95a03928dcdfbd7a307361/alejandra_jofre_ejercicio2pynb.ipynb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
files.upload()

df=pd.read_excel("BaseDeDatos.xlsx")
df

ColumnasOrdenadas=pd.DataFrame (df, columns=["Nombre","Apellido","Categoría","Matrícula","Salario","Fecha ingreso"])
ColumnasOrdenadas

Fax=df[df.Sección=="Fax"]
Fax

Copiadoras=df[df.Sección=="Copiadoras"]
Copiadoras

Impresoras=df[df.Sección=="Impresoras"]
Impresoras

SumaSalario=df.Salario.sum()
SumaSalario